version: '3'

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    networks:
      - customnet
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - customnet

networks:
  customnet:
    driver: bridge
